language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - android-22
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22

before_script:
    - echo no | android create avd --force --name test --target android-22 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window -no-boot-anim &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script:
    - ./gradlew connectedAndroidTest
    - cat lib/build/outputs/androidTest-results/connected/*.xml
